Algoritmo "Formula de Bhaskara"

Var

   X1, X2, A, B, C: Real

Inicio
escreva ("Escreva o valor de A: ")
leia (A)
escreva ("Escreva o valor de B: ")
leia (B)
escreva ("Escreva o valor de C: ")
leia (C)

X1 <- (-B + RaizQ((exp(b,2)) + (-B*A*(C)))) /(2*A)
X2 <- (-B - RaizQ((exp(b,2)) + (-B*A*(C)))) /(2*A)

escrevaL("X1 É IGUAL A", X1," E X2 É IGUAL A", X2)

escreva("X1 é diferete de X2? ", X1<>X2)

//Portanto,a=1 b=4 c=-21 x1=3 e x2=-7

Fimalgoritmo
